import type { Category, Resource } from "@/types";

export const categories: Category[] = [
  { name: "Open Source Apps", slug: "open-source-apps", icon: "Code2", description: "Auditable software from public repositories and trusted maintainers.", count: 12840 },
  { name: "Indie Games", slug: "indie-games", icon: "Gamepad2", description: "Free playable indie projects, jam builds and creator-approved downloads.", count: 3260 },
  { name: "Creative Commons Music", slug: "creative-commons-music", icon: "Music2", description: "Albums, loops and sound packs with clear attribution rules.", count: 9510 },
  { name: "Public Domain Movies", slug: "public-domain-movies", icon: "Film", description: "Classic films, archive footage and rights-cleared video material.", count: 1420 },
  { name: "Ebooks", slug: "ebooks", icon: "BookOpen", description: "Public-domain books, manuals, zines and research texts.", count: 22100 },
  { name: "Design Assets", slug: "design-assets", icon: "Palette", description: "Icons, UI kits, mockups, textures and brand-safe templates.", count: 6880 },
  { name: "Developer Tools", slug: "developer-tools", icon: "Terminal", description: "CLIs, libraries, SDKs and utilities for builders.", count: 17450 },
  { name: "Datasets", slug: "datasets", icon: "Database", description: "Open data for AI, analytics, education and research.", count: 4520 },
  { name: "Education", slug: "education", icon: "GraduationCap", description: "Courses, slides, labs, notebooks and learning packs.", count: 7810 },
  { name: "Other", slug: "other", icon: "Boxes", description: "Curated resources that do not fit the main categories.", count: 940 }
];

export const resources: Resource[] = [
  {
    id: "r_001",
    title: "Atlas Note — Open Source Knowledge Vault",
    slug: "atlas-note-open-source-notes",
    category: "Open Source Apps",
    categorySlug: "open-source-apps",
    license: "MIT",
    licenseSlug: "mit",
    shortDesc: "Markdown-first note system for teams and solo builders.",
    description: "Atlas Note is a local-first, Markdown-centered knowledge vault built for builders who want clean exports, backlinks, tagging, fast search and a transparent codebase. It is designed for documentation, personal knowledge management and small-team operations.",
    downloads: 184200,
    rating: 4.8,
    ratingCount: 3912,
    author: "Nexus Demo Collective",
    authorUrl: "https://github.com/",
    addedAt: "2026-04-18",
    size: "38 MB",
    tags: ["notes", "markdown", "productivity", "open-source"],
    verified: true,
    safeDownload: true,
    trustScore: 96,
    officialUrl: "https://github.com/",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1483058712412-4245e9b90334?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80"
    ],
    badges: ["verified", "open-source", "safe-download"]
  },
  {
    id: "r_002",
    title: "Neon Sprites CC0 Pack",
    slug: "neon-sprites-cc0-pack",
    category: "Design Assets",
    categorySlug: "design-assets",
    license: "CC0",
    licenseSlug: "cc0",
    shortDesc: "Cyberpunk sprite sheets, UI frames and transparent HUD assets.",
    description: "A CC0 visual pack containing layered sprites, UI frames, HUD decorations and neon-inspired interface fragments for games, prototypes and educational projects. Includes source files and export-ready PNGs.",
    downloads: 122450,
    rating: 4.7,
    ratingCount: 2150,
    author: "Pixel Forge Public Lab",
    authorUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    addedAt: "2026-04-21",
    size: "420 MB",
    tags: ["sprites", "cc0", "ui-kit", "game-assets"],
    verified: true,
    safeDownload: true,
    trustScore: 94,
    officialUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=1200&q=80"
    ],
    badges: ["verified", "public-domain", "safe-download"]
  },
  {
    id: "r_003",
    title: "Civic Data — Clean Air Pack",
    slug: "civic-data-clean-air-pack",
    category: "Datasets",
    categorySlug: "datasets",
    license: "CC0",
    licenseSlug: "cc0",
    shortDesc: "Open environmental dataset pack for dashboards and research prototypes.",
    description: "A curated open dataset bundle focused on air quality, sensor stations, city zones and aggregate trend metrics. Includes CSV files, metadata, examples and starter notebooks for civic-tech experiments.",
    downloads: 98320,
    rating: 4.6,
    ratingCount: 842,
    author: "Open Civic Lab",
    authorUrl: "https://data.gov/",
    addedAt: "2026-03-30",
    size: "2.1 GB",
    tags: ["dataset", "air-quality", "civic-tech", "education"],
    verified: true,
    safeDownload: true,
    trustScore: 91,
    officialUrl: "https://data.gov/",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80"
    ],
    badges: ["verified", "public-domain", "safe-download"]
  },
  {
    id: "r_004",
    title: "OrbitJam: Free Indie Space Runner",
    slug: "orbitjam-free-indie-space-runner",
    category: "Indie Games",
    categorySlug: "indie-games",
    license: "Freeware",
    licenseSlug: "freeware",
    shortDesc: "Fast free arcade runner from a public game jam page.",
    description: "OrbitJam is a lightweight arcade runner distributed by its creator for free from the official source page. The NexusHub listing links only to the creator-approved download and stores no game files directly.",
    downloads: 75104,
    rating: 4.3,
    ratingCount: 1033,
    author: "Small Star Studio",
    addedAt: "2026-04-02",
    size: "190 MB",
    tags: ["indie", "arcade", "game-jam", "free"],
    verified: true,
    safeDownload: true,
    trustScore: 88,
    officialUrl: "https://itch.io/games/free",
    image: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=1200&q=80"
    ],
    badges: ["verified", "safe-download"]
  },
  {
    id: "r_005",
    title: "Commons Loops — Dark Ambient Vol. 1",
    slug: "commons-loops-dark-ambient-vol-1",
    category: "Creative Commons Music",
    categorySlug: "creative-commons-music",
    license: "CC BY 4.0",
    licenseSlug: "cc-by-4-0",
    shortDesc: "Attribution-ready ambient loops for films, streams and games.",
    description: "A Creative Commons music pack containing stems, loops and one-shot effects with clear attribution requirements. Ideal for video creators, game prototypes and learning projects.",
    downloads: 64280,
    rating: 4.5,
    ratingCount: 1710,
    author: "Nocturne Commons",
    authorUrl: "https://creativecommons.org/licenses/by/4.0/",
    addedAt: "2026-04-12",
    size: "860 MB",
    tags: ["music", "cc-by", "loops", "ambient"],
    verified: true,
    safeDownload: true,
    trustScore: 92,
    officialUrl: "https://creativecommons.org/licenses/by/4.0/",
    image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=1200&q=80"
    ],
    badges: ["verified", "creative-commons", "safe-download"]
  },
  {
    id: "r_006",
    title: "Terminal Forge CLI Toolkit",
    slug: "terminal-forge-cli-toolkit",
    category: "Developer Tools",
    categorySlug: "developer-tools",
    license: "Apache-2.0",
    licenseSlug: "apache-2-0",
    shortDesc: "Open CLI utilities for scaffolding, linting and release automation.",
    description: "Terminal Forge bundles safe project scaffolding helpers, release checklists and typed configuration validators. It is distributed under Apache-2.0 and designed for modern JavaScript and TypeScript teams.",
    downloads: 54330,
    rating: 4.9,
    ratingCount: 2890,
    author: "Forge Tools Org",
    authorUrl: "https://github.com/",
    addedAt: "2026-04-26",
    size: "12 MB",
    tags: ["cli", "developer-tools", "typescript", "automation"],
    verified: true,
    safeDownload: true,
    trustScore: 97,
    officialUrl: "https://github.com/",
    image: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80"
    ],
    badges: ["verified", "open-source", "safe-download"]
  },
  {
    id: "r_007",
    title: "Public Shelf — Gothic Classics EPUB Bundle",
    slug: "public-shelf-gothic-classics-epub-bundle",
    category: "Ebooks",
    categorySlug: "ebooks",
    license: "Public Domain",
    licenseSlug: "public-domain",
    shortDesc: "Public-domain gothic literature bundle in EPUB and PDF formats.",
    description: "A curated public-domain reading pack containing metadata, cover art, EPUB files and PDF versions sourced from public archive listings. Great for schools, libraries and offline reading collections.",
    downloads: 48950,
    rating: 4.4,
    ratingCount: 930,
    author: "Public Shelf Index",
    authorUrl: "https://www.gutenberg.org/",
    addedAt: "2026-02-22",
    size: "310 MB",
    tags: ["ebooks", "public-domain", "literature", "education"],
    verified: true,
    safeDownload: true,
    trustScore: 93,
    officialUrl: "https://www.gutenberg.org/",
    image: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1200&q=80"
    ],
    badges: ["verified", "public-domain", "safe-download"]
  },
  {
    id: "r_008",
    title: "Signal Academy — Web Security Starter Course",
    slug: "signal-academy-web-security-starter-course",
    category: "Education",
    categorySlug: "education",
    license: "CC BY 4.0",
    licenseSlug: "cc-by-4-0",
    shortDesc: "Legal web security labs focused on defensive engineering.",
    description: "A defensive web security curriculum with slides, safe labs, checklists and example fixes. It emphasizes responsible learning, validation, XSS prevention, authentication hygiene and deployment hardening.",
    downloads: 33870,
    rating: 4.7,
    ratingCount: 650,
    author: "Signal Academy",
    addedAt: "2026-04-28",
    size: "96 MB",
    tags: ["education", "security", "web", "defensive"],
    verified: true,
    safeDownload: true,
    trustScore: 95,
    officialUrl: "https://owasp.org/",
    image: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80"
    ],
    badges: ["verified", "creative-commons", "safe-download"]
  },
  {
    id: "r_009",
    title: "Archive Noir — Public Domain Film Cuts",
    slug: "archive-noir-public-domain-film-cuts",
    category: "Public Domain Movies",
    categorySlug: "public-domain-movies",
    license: "Public Domain",
    licenseSlug: "public-domain",
    shortDesc: "Rights-cleared noir clips and public-domain film references.",
    description: "A public-domain film collection with archive links, metadata, usage notes and editorial tags. NexusHub does not host the films directly; downloads are routed to legal public archive sources.",
    downloads: 30610,
    rating: 4.2,
    ratingCount: 420,
    author: "Archive Noir Index",
    authorUrl: "https://archive.org/",
    addedAt: "2026-01-09",
    size: "Varies",
    tags: ["movies", "public-domain", "archive", "film"],
    verified: true,
    safeDownload: true,
    trustScore: 86,
    officialUrl: "https://archive.org/",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517602302552-471fe67acf66?auto=format&fit=crop&w=1200&q=80"
    ],
    badges: ["verified", "public-domain", "safe-download"]
  },
  {
    id: "r_010",
    title: "ForgePress Minimal Blog Template",
    slug: "forgepress-minimal-blog-template",
    category: "Other",
    categorySlug: "other",
    license: "GPL-3.0",
    licenseSlug: "gpl-3-0",
    shortDesc: "Clean legal blog template for personal publishing projects.",
    description: "A minimal GPL blog template with accessible components, dark mode, RSS-ready content structure and SEO metadata. Useful as a starter for public writing and project journals.",
    downloads: 18890,
    rating: 4.1,
    ratingCount: 270,
    author: "ForgePress Community",
    addedAt: "2026-03-04",
    size: "24 MB",
    tags: ["template", "blog", "gpl", "starter"],
    verified: false,
    safeDownload: true,
    trustScore: 79,
    officialUrl: "https://wordpress.org/",
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80"
    ],
    badges: ["safe-download"]
  }
];

export const comments = [
  { author: "Mira", score: 5, body: "Clean listing, source link checks out and the license block made it easy to verify usage rights." },
  { author: "Kay", score: 4, body: "Useful metadata and fast download from the official page. Would love more screenshots." },
  { author: "North", score: 5, body: "The trust score and safety scan format are exactly what community catalogues need." }
];
